name: Node.js CI

on:
  push:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      env:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
      with:
        username: ${{ env.username }}
        password: ${{ env.password }}
    - name: Get verion
      id: image
      run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"  
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: risilze/cicd_project:${{ steps.image.outputs.version}}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get verion
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
      
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Checkout kustomize repository
        uses: actions/checkout@v2
        env: 
          ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          repository: rirub/cicd_manifests
          ref: main
          token: ${{env.ACTION_TOKEN }}
          path: cicd_manifests

      - name: Update Kubernetes resources
        run: |
          cd cicd_manifests/overlays/dev/
          kustomize edit set image risilze/cicd_project:${{ steps.image.outputs.version }}
          cat kustomization.yaml
          

      - name: Commit files
        run: |
          cd cicd_manifests
          git config --global user.email "risilze@github.com"
          git config --global user.name "rirub"
          git commit -am "Update image tag"
          git push -u origin dev


    
        
        
        
  
        
