name: Node.js CI

on:
  push:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      env:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
      with:
        username: ${{ env.username }}
        password: ${{ env.password }}
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      env:
        repository: ${{ cicd_project }}
      with:
        push: true
        tags: ${{ env.username }}/${{repository}}:${{ github.sha }}
